### ISSUE TITLE
 Unable to resume activity ... Service Intent must be explicit

### ISSUE THREAD

**Issue by zezadas** [DexPatcher/dexpatcher-tool#1]
First, I want to thank you all the great work!!

I'm facing a issue, basically I have a application that is running fine, but when I try it to use it on AndroidStudio, running the project I get this error https://paste.kde.org/psfd4kmuk
No Java modification has been made.
I have been reading and it has something to do with Intents and SDK version. 
can you check if it's a AndroidStudio/your Tools or my lack of knowledge.

Thanks
Regards, zezadas

**Comment by zezadas** [comment]
Here is my Android Studio project
https://github.com/zezadas/camera

**Comment by Lanchon** [comment]
first thing, you need to use apktool to decode then rebuild, sign and 
zipalign the app, and test if it works.

**Comment by zezadas** [comment]
that was not the problem, I already found it

it was on build.gradle

```
  minSdkVersion 19
    targetSdkVersion 19
    versionCode 1
    versionName "1.0"
```

I had to set minSdkVersion and targetSdkVersion to API 19 , it was set to 21 and API 21 as some differences in intent's

Thaks a lot... ;)
that, the fun begin :D

**Comment by Lanchon** [comment]
yes, you have to set those values to the original app or higher 
according to your needs.
sorry i wasnt on an PC to take a closer look quicker.
please do ask if u need help, always preferred if u ask in the public 
forum on xda if possible.

**Comment by zezadas** [comment]
yeah, I forgot those fields, maybe you can make that automatic and recognize from the original package.

I only created the issue here, because a thought it was some problem with the code, I have the xda thread subscribed ;)

Again, Thanks a Lot :D
Great Project ;)

**Comment by Lanchon** [comment]
lol i never noticed we were on github, i thought it was a private msg :)
still on cellphone

totally ok to log problems here.

no, i looked into that, cant do it. those numbers must be set during
gradles build setup phase for android plugin to work. however, the contents
of the apk library (ie, the decoded app) including the apktool YML file
holding the required fields arent known until the build execution phase
where the android libraries including the apklib are found and exploded
inside the build directory. causal relationships require that that info is
entered manually.

what can be done is a warning during build if there is a mismatch. but
parsing the files and all seems like a waste of time given that higher
priority items are in the todo list, such as apktool based rebuilding when
resource merging isnt required, for better fidelity to the original apk.

finally, those numbers really are a choice according to your needs, auto
setting would not be good. maybe u r importing several andoid libs or using
newer apis in ur code: those settings must be the superset of everything,
not just what the original app was.

also note that android build system suffers from this causality issue too:
it cant select the proper values according to your imported android libs,
it can only fail the build if you choose incorrent values.
