### ISSUE TITLE
Package name manifest

### ISSUE THREAD

**Issue by gambogo** [DexPatcher/dexpatcher-tool#12]
Hi Lanchon

I tried patching app without set package name identifier in manifest file or set the real package name identifier then the compiler show error. But when i set any package name, compiling successful.

Because i need to sign in app with google account so i think the package name must be original.
Can we remain the original package name for the app ?

Thank you so much

**Comment by Lanchon** [comment]
hi,

you are in the wrong project. please post your question in DexPatcher-gradle to get a proper response.

PS. yes, of course you can.
