### ISSUE TITLE
dexpatcher.jar lib How to use

### ISSUE THREAD

**Issue by KaustubhPatange** [DexPatcher/dexpatcher-tool#16]
Note : - I have read all the necessary documentations of this tool before creating this issue.

Earlier i was using this script in linux, now I have seen that .jar version of dexpatcher has been released. Also you said in your forum post that this is independent tool doesn't need any bundle. But problem is how to use it.. the basic filters (options) of setting apk is missing in this jar. 
No documentation found for this .jar version. So how to use it basically 

Thanks in Advance !

**Comment by Lanchon** [comment]
hi,

im sorry but i can't understand your issue. i dont know what you are trying to do. are you using the gradle plugins within android studio to modify an APK? are you using the deprecated linux scripts?

thanks!

**Comment by KaustubhPatange** [comment]
Nope I am trying to use it without android studio on windows only having SDK set up.


When I use java -jar dexpatcher.jar it gives some help section but there is not option to set-up-apk option for apk..to edit or ads scripts also make is missing..means I don't know how to use it in windows..so any idea

**Comment by Lanchon** [comment]
the dexpatcher tool (java -jar dexpatcher.jar) works on windows and everywhere. but it is the patching tool itself and nothing else. the commands you mention were deprecated eons ago.

do you want to patch an APK?

**Comment by KaustubhPatange** [comment]
yes I want to patch apk

**Comment by Lanchon** [comment]
then follow the "start here" section of the help.

you dont need to download anything (not even the jar). you have to clone 2 repos, as the help says.

then instead of opening android studio (since you dont want to use it) just run the command "gradlew build" in the main project directory of one of the 3 samples.

the process of cloning the -gradle-tools repo will download all the needed tools, dexpatcher included.

tell me how that goes.

**Comment by KaustubhPatange** [comment]
Sure will do it soon

**Comment by Lanchon** [comment]
were you able to make progress?

**Comment by KaustubhPatange** [comment]
Hey mate, currently my exams are going in college so..studying for that..
It will get over by this Monday... After that I will be trying dexpatcher..
Please bro wait till that time.. ! But first which two gits to compile... I
didn't get it?

**Comment by Lanchon** [comment]
lol :)
the big red START HERE section....
https://forum.xda-developers.com/android/software/tool-dexpatcher-modify-android-dex-apk-t3060854

**Comment by KaustubhPatange** [comment]
Alright! I am done with my all study stuffs, now coming to this part..!

I have cloned support tools and Samples, so I have observed the stuff..every directory contains a patched dir in which a script u have said.. Clone the objects and add an overlap codes.. But the thing is how to make it and how to compile that patched app.. Without android studio... For eg can I do something like this..

From support tools.. Decompile apk, grab classes.dex 
Use dexpatcher generate that auto layout with SRC folder and all .. And then again use dexpatcher to compile it.. So do we have such things to do.. 

Help Mate!
