### ISSUE TITLE
Could not create plugin of type 'PatchedAppPlugin'. ClassNotFoundException: PrepareLibraryTask

### ISSUE THREAD

**Issue by gb96** [DexPatcher/dexpatcher-tool#21]
Sample apps don't want to build in my environment:
- Windows 7 (SP1, 64-bit)
- Android Studio 3.0.1 (Build #AI-171.4443003, built on November 10, 2017)
- JRE: 1.8.0_152-release-915-b01 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Gradle 4.4.1 [gradle-v.txt](https://github.com/DexPatcher/dexpatcher-tool/files/1650634/gradle-v.txt)

Have tried both gradlew on command-line and build in Android Studio (gradle stacktrace below)
[gradle--stacktrace--debug.txt](https://github.com/DexPatcher/dexpatcher-tool/files/1650631/gradle--stacktrace--debug.txt)

**Comment by Lanchon** [comment]
please read the release notes!
https://github.com/DexPatcher/dexpatcher-gradle/releases

the sample apps ship with the appropriate gradle wrapper. android studio wants to upgrade gradle... dont! if you did, discard changes or clone repo again. "gradlew build" should work if you followed the instructions.

**Comment by Lanchon** [comment]
as the release notes state, Gradle v2.14.1 and v3.3 are supported. i prefer v2.14.1.

v4.4.1 is not supported. btw, the regular output of gradle is useful to me. debug output isn't.

**Comment by Lanchon** [comment]
also, please open gradle plugin issues in the proper project:
https://github.com/DexPatcher/dexpatcher-gradle

the dexpatcher-tool project is the command line dex modification tool, one of the many tools used by dexpatcher-gradle.

thanks!

**Comment by gb96** [comment]
Okay, thanks for the quick and detailed response!

**Comment by Lanchon** [comment]
please tell me if you were able to build.

**Comment by gb96** [comment]
Android Studio Build worked fine.
Command-line build failed (missing 'tools.jar').. I need to download and install JDK 1.8.0 because the JRE is missing tools.jar
I have JDK 9.0.1 however gradle < 4 does not work with JDK 9

`    FAILURE: Build failed with an exception. `
`
    * What went wrong:`
`    Could not determine java version from '9.0.1'.
`

**Comment by gb96** [comment]
Installed Oracle Java JDK 1.8.0_162-b12 and set it to be at the start of my PATH, command-line gradle now builds fine for patched-app sample.

**Comment by Lanchon** [comment]
thanks!

instead of modifying PATH you can set the java to use for gradle in `gradle.proeprties` like this:
`org.gradle.java.home=C:/Program Files/Java/jdk1.8.0_xxx`

https://docs.gradle.org/2.14.1/userguide/build_environment.html

hope you like dxp
