### ISSUE TITLE
Error: target not found

### ISSUE THREAD

**Issue by kedorlaomer** [DexPatcher/dexpatcher-tool#22]
I would like to patch an overloaded method; the [source](https://raw.githubusercontent.com/sqlcipher/android-database-sqlcipher/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java) says:

```java
    /**
     * Equivalent to openDatabase(file.getPath(), password, factory, CREATE_IF_NECESSARY, databaseHook).
     */
    public static SQLiteDatabase openOrCreateDatabase(File file, String password, CursorFactory factory, SQLiteDatabaseHook databaseHook) {
        return openOrCreateDatabase(file, password, factory, databaseHook, null);
    }

    /**
     * Equivalent to openDatabase(path, password, factory, CREATE_IF_NECESSARY, databaseHook).
     */
    public static SQLiteDatabase openOrCreateDatabase(String path, String password, CursorFactory factory, SQLiteDatabaseHook databaseHook) {
        return openDatabase(path, password, factory, CREATE_IF_NECESSARY, databaseHook);
    }

    /**
     * Equivalent to openDatabase(path, password, factory, CREATE_IF_NECESSARY, databaseHook).
     */
    public static SQLiteDatabase openOrCreateDatabase(File file, String password, CursorFactory factory, SQLiteDatabaseHook databaseHook,
                                                      DatabaseErrorHandler errorHandler) {
        return openOrCreateDatabase(file == null ? null : file.getPath(), password, factory, databaseHook, errorHandler);
    }

    public static SQLiteDatabase openOrCreateDatabase(String path, String password, CursorFactory factory, SQLiteDatabaseHook databaseHook,
                                                      DatabaseErrorHandler errorHandler) {
        return openDatabase(path, password == null ? null : password.toCharArray(), factory, CREATE_IF_NECESSARY, databaseHook, errorHandler);
    }

    public static SQLiteDatabase openOrCreateDatabase(String path, char[] password, CursorFactory factory, SQLiteDatabaseHook databaseHook) {
      return openDatabase(path, password, factory, CREATE_IF_NECESSARY, databaseHook);
    }

    public static SQLiteDatabase openOrCreateDatabase(String path, char[] password, CursorFactory factory, SQLiteDatabaseHook databaseHook,
                                                      DatabaseErrorHandler errorHandler) {
        return openDatabase(path, password, factory, CREATE_IF_NECESSARY, databaseHook, errorHandler);
    }

    /**
     * Equivalent to openDatabase(file.getPath(), password, factory, CREATE_IF_NECESSARY).
     */
    public static SQLiteDatabase openOrCreateDatabase(File file, String password, CursorFactory factory) {
        return openOrCreateDatabase(file, password, factory, null);
    }

    /**
     * Equivalent to openDatabase(path, password, factory, CREATE_IF_NECESSARY).
     */
    public static SQLiteDatabase openOrCreateDatabase(String path, String password, CursorFactory factory) {
      return openDatabase(path, password, factory, CREATE_IF_NECESSARY, null);
    }

    /**
     * Equivalent to openDatabase(path, password, factory, CREATE_IF_NECESSARY).
     */
    public static SQLiteDatabase openOrCreateDatabase(String path, char[] password, CursorFactory factory) {
      return openDatabase(path, password, factory, CREATE_IF_NECESSARY, null);
    }
```

The method is heavily overloaded, and I would like to apply the following patch:

```java
    @DexEdit(target = "openOrCreateDatabase")
    public static SQLiteDatabase source_openOrCreateDatabase(File file, String string2, CursorFactory cursorFactory) {
        throw null;
    }

    @DexAdd
    public static SQLiteDatabase openOrCreateDatabase(File file, String string2, CursorFactory cursorFactory) {
        SQLiteDatabase rv = source_openOrCreateDatabase(file, string2, cursorFactory);
        log("database created");
        return rv;
    }
```

Dexpatcher says (version 1.6):

````
dxp-make-patch: done: patch.dex
info: read 'source.dex'
info: read 'patch.dex'
info: type 'net.sqlcipher.database.SQLiteDatabase': direct method '<init>():void': (SQLiteDatabase.java:9): default ignore
error: type 'net.sqlcipher.database.SQLiteDatabase': direct method 'source_openOrCreateDatabase(java.io.File, java.lang.String, net.sqlcipher.database.CursorFactory):net.sqlcipher.database.SQLiteDatabase': target 'openOrCreateDatabase': (SQLiteDatabase.java:12): target not found
info: type 'net.sqlcipher.database.SQLiteDatabase': virtual method 'onAllReferencesReleased():void': (SQLiteDatabase.java:26): default ignore
1 error(s), 0 warning(s)
````

How can I tell dexpatcher which method to replace?

**Comment by gb96** [comment]
Since the target class is open-source, maybe you can `@DexReplace` the whole class?  Copy and paste the source and then change whatever you like without needing any further annotations.

**Comment by Lanchon** [comment]
hi,

> info: type 'net.sqlcipher.database.SQLiteDatabase': virtual method 'onAllReferencesReleased():void': (SQLiteDatabase.java:26): default ignore

never use default=xxx in DexEdit unless you **have to** (to tag compiler-generated methods). always use explicit DexIgnores. trust me, default= will stab you in the back, just don't.

> dxp-make-patch: done: patch.dex

wtf!!! you are using the deprecated automation scripts from a million years ago! those are deprecated and completely unsupported. if i had to guess, you are patching a multidex apk using those scripts which don't support it. are you?

the preferred way to patch apks is using the gradle plugin, which lets you patch resources and everything else in the apk (but is a bit more complex). you can use the patched-app sample as a base. if for whatever reason you just want to patch the dex code (without disassembling and reassembling other parts of the apk), you can modify the patched-jar sample (extensively) if you know a bit of gradle. otherwise you can update the scripts you are using to multidex.

**Comment by Lanchon** [comment]
otherwise make sure you are using the right File and CursorFactory classes (one could be coming from the wrong package). please report progress.

**Comment by kedorlaomer** [comment]
`@DexReplace` on the whole class sounds like a somewhat bad idea to me for two reasons:

+ It's “pure luck” that I have the source available; actually, the `.class` I found after decompiling the `.dex` is slightly (but functionally) different from the source.

+ The fact that overloaded methods cannot be patched (or can they, and I don't know how?) is still a bug, isn't it?

`File` is `java.io.File` as expected; `CursorFactory` is some interface I copy-pasted into the source.

Additionally, I cannot recompile the class since it produces nested classes that I cannot remove (I removed all directly nested `interface`s, `class`es, `enum`s and implemented/subclassed interfaces and abstract classes in the style of `new Runnable() {public void run() {}}` and there is still some nested class left somewhere; furthermore, the whole codebase — thousands of LOC — expects a nested class; finally, there are references to classes and constants that I cannot find anywhere in the sources …!).

The apk I'm trying to patch is not multidex as far as I can see. I cannot reproduce any of the samples from https://github.com/DexPatcher/dexpatcher-gradle-samples (I'll file a bug if nothing helps). Altogether not very surprising because in my experience, the toolchain for android is always prone to break when touched lightly, so I was very happy finding something that doesn't seem to require gradle, only to be forced to use gradle again!

**Comment by Lanchon** [comment]
> DexReplace on the whole class sounds like a somewhat bad idea

it is!

> The fact that overloaded methods cannot be patched (or can they, and I don't know how?) is still a bug, isn't it?

they can be patched, there is no such bug or problem in dxp.

> I cannot reproduce any of the samples

you should be able to. please open a different issue if you need help building the samples. make sure you describe your platform and all steps you do completely. you are doing something wrong for sure.

> the toolchain for android is always prone to break

gradle builds are very dependable. gradle is not brittle.

------------

you got 3 issues:
1) you cannot build samples
2) you are using deprecated tools
3) with wich you cannot patch your app

for 3)... can you post your complete project online? can you post the apk? can you post the complete java patch file in question? or can you send these things to me? unless you provide more info, there is not enough info on your report to help you.

**Comment by Lanchon** [comment]
@kedorlaomer, will you follow up on this?

**Comment by kedorlaomer** [comment]
Since there's only one problem and the rest are corollaries, I'll try to install the Android toolchain on a fresh and untainted box and file a new bug report if this doesn't work.

**Comment by Lanchon** [comment]
you don't need to. if you want to build the samples, follow the instructions on any computer. if you have any problems, post a new issue describing setup (OS, etc), what you did, and what the error is.

EDIT: but please open said issue on the right project for it:
https://github.com/DexPatcher/dexpatcher-gradle/issues
thanks!

**Comment by Lanchon** [comment]
apparently abandoned
