### ISSUE TITLE
core.jar (core-pj.jar) patch support

### ISSUE THREAD

**Issue by ViRb3** [DexPatcher/dexpatcher-tool#24]
I noticed in the script that core cannot be patched (yet). I am just curious why such a limitation exists, and if there's any way to work it around, even if manually?
I tried manually patching my core-oj.jar, but after I replaced it in the system, it no longer boots. Given, it is an odexed ROM, but by deleting the odex files I was able to get a services.jar patch to work perfectly.

Thanks!

**Comment by Lanchon** [comment]
i dont know what you are talking about. why cant it be patched? what script?

**Comment by ViRb3** [comment]
haystack/patch-fileset:
```bash
    if [ "$name" == "core.jar" ] || [ "$name" == "core-libart.jar" ]; then
        error "patching core jars not yet supported by these scripts"
    fi
```

is what I was looking at. Just realized that I posted in the wrong repo, my apologies.

**Comment by Lanchon** [comment]
yes, different project. anyway...

im not supporting oreo with haystack so far. where is your core-pj.jar
coming from?

**Comment by ViRb3** [comment]
Haystack works splendidly on Oreo, ODEXed even. I only had to deodex my `services.jar` and then delete `/system/framework/oat/arm64/services.odex`
I tried to do the same for `core-oj.jar`, but it was a lot different:
* no files under `/system/framework/oat/arm64`, but rather under `/system/framework/arm64`
* no odex+vdex file, but rather `boot-core-oj.oat,` `boot-core-oj.art` and `boot-core-oj.vdex` (note the prefix)

I managed to deodex the jar using [SmaliEx](https://github.com/testwhat/SmaliEx), but after replacing the original and deleting those 3 files under `/system/framework/arm64`, my phone doesn't boot...

I originally want to patch `core.jar`, but it seems like it is split in two files in Oreo, thus my attempts to patch `core-oj.jar`. 

Any ideas how I could overcome this? Thank you!

**Comment by Lanchon** [comment]
> Haystack works splendidly on Oreo

i've heard, but it is unsupported.

> I only had to deodex my services.jar
> I tried to do the same for core-oj.jar

nope!!! optimizing (odexing, quickening, compiling, whatever you wanna call it) is a **global** operation. you can't deodex and modify a single file! if you mod services.jar, you need to deodex everything that might depend on it (it will be odexed again on runtime) -ie, the complete android framework-, and reoptimize any apps you might have installed;

**Comment by ViRb3** [comment]
It now makes sense why there's a boot.oat file and a bunch of optimized files prefixed with boot-. I deodexed the whole framework and the ROM ran, indeed. Thanks so much for the explanations!
My last question is why is everything so utterly slow? Even after using the phone for an hour, performance is still far from the pre-optimized state. I do not recall such drastic performance issues when running a deodexed ROM.
Thanks!

**Comment by Lanchon** [comment]
whatever version of android you are using might do a native compile on a maintenance schedule and maybe when charging, so you may need to wait for 2 days while charging at night. but there are also commands you can issue to force an optimize. i don't know much about android, especially recent ones; google and test. thanks!
