### ISSUE TITLE
Does it work with apps that are built with Android Studio 3.2/Gradle 4.6 and targeted to Android Pie?

### ISSUE THREAD

**Issue by duanjason** [DexPatcher/dexpatcher-tool#25]
Hello,

This is more a question than defect. 

Does it work with apps that are built with Android Studio 3.2/Gradle 4.6/Java 8 and targeted to Android Pie?

Thanks

**Comment by Lanchon** [comment]
hey, i'm working on it now.

you are in the wrong project. subscribe to releases of this project to get an update:
https://github.com/DexPatcher/dexpatcher-gradle
