### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by beshoo** [DexPatcher/dexpatcher-tool#29]
Dear All.
First, I am very new to patching world, so please be patient with me.
Usually, if I want to patch apk.

> 1- Extract dex file from the apk,
> 2- Use dex2jar in order to see the java code via (**jd-gui**) [Some time it fails to decode some parts of the Java bite code]
> 3- locate the method I want to patch - hopefully it decoded via (**jd-gui**).
> 4- add/edit the method via Notepad++
> 5- Decode the apk via  apktool 2.4.1 with the "--only-main-classes" decode option. 
> 6- locate the method inside the *smali* file.
> 7- Go to **http://java2smali.com/** to convert java to smali.
> 8- Replace the method with the new one.
> 9- compile and run.

Now I found this project, but honestly, I don't understand how to use it.
I have APK which I want to add an *aar* to it and call this lib on the apk start... this aar does not belong to the apk, but I want to force it to be included in the APK.

I will be thankful if you redirect me to how to install / use *dexpatcher-tool*, i believe i am missing something.

**Comment by Lanchon** [comment]
i'm sorry. documentation in this project is limited. the docs you are asking for dont exist for now. but most people can cope with what is already documented. you dont install this tool, you just use it. follow the steps in the "start here" section of the docs to start using the tools.

**Comment by Lanchon** [comment]
and if you have general usage question, try the XDA thread. thanks!

**Comment by beshoo** [comment]
@Lanchon 
Thanks for the reply. 
Well, usually the open an issue after following the provided documentation. 

I cloned the repo. To the android studio, then what? 

I found the apk files, ok i found 3 project in the same project, ok what now... 

I understand that this lib will find the apk but how to start it. How to see the java code... How to start... 

Well i viewed all xda post, a lot of users asking for the same thing, how to start using it. 

It will be very kind if you show as example how to decode something, any apk from the market, then how to edit smali or java code if that applies, and how to rebuild it. 

How to add an aar lib. It will be very useful and time saver, i found some long replies in sdk from you regarding some questions. That is great. We just need half of that as how to start.

**Comment by Lanchon** [comment]
> I found the apk files, ok i found 3 project in the same project, ok what now...

it's *several* projects in the same *repo*. they are independent projects (although there is a centralized build.gradle to allow building all of them at once from the command line

> Start with the 'patched-app' sample: open the project with Android Studio, disable instant run, and run or debug your patched app!

> a lot of users asking for the same thing, how to start using it.

i will answer that in the xda thread since you asked there too.
