### ISSUE TITLE
Do you have any plans to support AGP7.0 in the future

### ISSUE THREAD

**Issue by oooooooko** [DexPatcher/dexpatcher-tool#38]
Do you have any plans to support AGP7.0 in the future

**Comment by Lanchon** [comment]
this corresponds to dexpatcher-gradle, not dexpatcher-tool.

i have no plans for now. can you elaborate on why you need AGP7 support?

**Comment by oooooooko** [comment]
> 这对应于 dexpatcher-gradle，而不是 dexpatcher-tool。
> 
> 我现在没有计划。您能详细说明为什么需要 AGP7 支持吗？

Yes, when I use dexpatcher-gradle, AS will prompt that the AGP version is too low, and it still prompts this error after lowering the version

![image](https://github.com/DexPatcher/dexpatcher-tool/assets/48895716/4390f5c6-7a92-49d4-9b72-e696e83fa15c)

Or is there any solution you can provide, thank you

**Comment by Lanchon** [comment]
as stated here:
https://github.com/DexPatcher/dexpatcher-gradle/releases/tag/v2.0.0

use the proper AGP version:
> Android Gradle plugin v3.2 though v3.4.2.

**Comment by ffdsss** [comment]
> as stated here: https://github.com/DexPatcher/dexpatcher-gradle/releases/tag/v2.0.0
> 
> use the proper AGP version:
> 
> > Android Gradle plugin v3.2 though v3.4.2.

Where can I download version 2.1.3 from?

![image](https://github.com/DexPatcher/dexpatcher-tool/assets/48895716/9af1454c-a09d-4f9f-bce1-8592c716cf02)

**Comment by ffdsss** [comment]
> as stated here: https://github.com/DexPatcher/dexpatcher-gradle/releases/tag/v2.0.0
> 
> use the proper AGP version:
> 
> > Android Gradle plugin v3.2 though v3.4.2.

I added 'aapt2' in the project's build.gradle, but after applying the plugin in build.gradle in the app, it prompts Could not initialize class. What is the reason for this?

![image](https://github.com/DexPatcher/dexpatcher-tool/assets/48895716/adeb32cd-6c1c-462d-b1ba-275853aba6bd)

![image](https://github.com/DexPatcher/dexpatcher-tool/assets/48895716/82fd5a38-85e2-46e9-b0cb-8cf38f9c2719)

**Comment by Lanchon** [comment]
i don't know. if you can't debug it, you have to post a complete project and maybe someone might help you.

at a minimum post COMPLETE logs of the build process, and state your gradle, and AGP versions.

also, please open separate issues for different problems.


> I added 'aapt2' in the project's build.gradle

why?
